import Head from 'next/head'
import NavBar from '../components/Navbar'
import SongShow from '../components/SongShow'
import { MainWrap } from '../styles/MainWrap'
import Billie from "../public/img/billie.png"
import Image from 'next/image'
import { useRouter } from 'next/router'



export default function Home() {
  const router = useRouter()
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <MainWrap>
     <div className='nav'>
     <NavBar/>
     </div>
      <div className='mainBody'>
          <div className='mainInfo'>
            <h1 className='mainHeader'>Musiqani haqiqiy ma&apos;no&apos;sini bilib oling</h1>
            <p className='mainSub'>Endi biz bilan chet el musiqasini
            aniq tushinishingiz mumkin</p>

            <button className='searchBtn'>Izlash</button>
          </div>

          <div className="mainPicContainer">
            <div className="mainPic">
              <Image src={Billie} alt="billie eillish" fill />
            </div>
          </div>

          <h4 className='trendListHeader'>Top</h4>
          <div className='trendList'>
           <div onClick={()=> router.push("/lyrics", {query: {name: "earthSong"}})}>
           <SongShow songName="Earth Song" songArtist="Michael Jackson" songImg="/img/earthsong.png"/>
           </div>
           <div onClick={()=> router.push("/lyrics",  {query: {name: "stan"}})}>
           <SongShow songName="Stan" songArtist="Eminem" songImg="/img/em.png"/>
           </div>
           <div onClick={()=> router.push("/lyrics", {query: {name: "onlyWoman"}})}>
           <SongShow songName="Only A Woman" songArtist="Enrique Iglesias" songImg="/img/onlywoman.png"/>
           </div>
            <div onClick={()=> router.push("/lyrics", {query: {name: "comingHome"}})}>
            <SongShow songName="Coming Home" songArtist="Enrique Iglesias" songImg="/img/cominghome.png"/>
            </div>
           <div onClick={()=> router.push("/lyrics", {query: {name: "billieJean"}})}>
           <SongShow songName="Billie Jean" songArtist="Michael Jackson" songImg="/img/billiejean.png"/>
           </div>
           <div onClick={()=> router.push("/lyrics", {query: {name: "esape"}})}>
           <SongShow songName="Escape" songArtist="Enrique Iglesias" songImg="/img/escape.png"/>
           </div>
 
  


          </div>
      </div>
    </MainWrap>
    
    </div>
    
  )
}
