import Head from 'next/head'
import NavBar from '../components/Navbar'
import SongShow from '../components/SongShow'
import { MainWrap } from '../styles/MainWrap'
import Billie from "../public/img/billie.png"
import Image from 'next/image'
import { useRouter } from 'next/router'



export default function Home() {
  const router = useRouter()
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <MainWrap>
     <div className='nav'>
     <NavBar/>
     </div>
      <div className='mainBody'>
          <div className='mainInfo'>
            <h1 className='mainHeader'>Musiqani haqiqiy ma&apos;no&apos;sini bilib oling</h1>
            <p className='mainSub'>Endi biz bilan chet el musiqasini
            aniq tushinishingiz mumkin</p>

            <button className='searchBtn'>Izlash</button>
          </div>

          <div className="mainPicContainer">
            <div className="mainPic">
              <Image src={Billie} alt="billie eillish" fill />
            </div>
          </div>

          <h4 className='trendListHeader'>Top</h4>
          <div className='trendList'>
           <div onClick={()=> router.push("/lyrics")}>
           <SongShow songName="Perfect" songArtist="Ed Sheeran" songImg="/img/ed2.png"/>
           </div>
           <div onClick={()=> router.push("/lyrics")}>
           <SongShow songName="Stan" songArtist="Eminem" songImg="/img/em.png"/>
           </div>
           <div onClick={()=> router.push("/lyrics")}>
           <SongShow songName="Desert Rose" songArtist="Sting" songImg="/img/sting.png"/>
           </div>
            <div onClick={()=> router.push("/lyrics")}>
            <SongShow songName="Blinding Lights" songArtist="The Weeknd" songImg="/img/bl.png"/>
            </div>
           <div onClick={()=> router.push("/lyrics")}>
           <SongShow songName="In The End" songArtist="Linkin Park" songImg="/img/linkinpark.png"/>
           </div>
           <div onClick={()=> router.push("/lyrics")}>
           <SongShow songName="Just Like You" songArtist="NF" songImg="/img/likeyou.png"/>
           </div>
 
  


          </div>
      </div>
    </MainWrap>
    
    </div>
    
  )
}
